met client requirement for hello world console printing
JaysGitLab/cs-5666-greeting-mattstone22133 pull request #3
Opened 2017-01-31 16:07 UTC by mattstone22133

Please do a code review so that we may add the feature to the application.

2017-02-01 02:49 UTC, fenwickjb requested changes

2017-02-01 02:49 UTC, fenwickjb commented on HelloWorld.java
> +	System.out.println("Hello World!");
Printed string does not meet specification.

2017-02-01 02:49 UTC, fenwickjb commented
Would be better if testing were automated and not relying on humans who are error-prone. ;-)
Check this out...
http://stackoverflow.com/questions/1119385/junit-test-for-system-out-println

Also, it might help if you assign me as a "reviewer" (see panel to the right).

2017-02-01 23:47 UTC, mattstone22133 commented
@fenwickjb Changed the class to better represent string and added a new unit test. 

*do we need to create a new pull request if changes are made to the commit?*

2017-02-03 03:15 UTC, fenwickjb requested changes

2017-02-03 03:15 UTC, fenwickjb commented on TestHelloWorld.java
> +		//save the system.in and system.out
Lines 11-17 are "before the test" setup types of activities. JUnit provides a nice mechanism for these setup and teardown types of things.

2017-02-03 14:10 UTC, merged